name: Deploy test
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - name: Kết nối ssh linux-và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME}}
        password: ${{ secrets.PASSWORD}}
        port: 22
        script: |
          cd /var/www/test_cicd_node_v2
          git pull
          . $HOME/.nvm/nvm.sh
          nvm use
          npm install --omit-dev
          pm2 delete all
          pm2 start app.js
